version: '2'
services:
    mysql:
        container_name: clinicasql
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: web_1  
            MYSQL_USER: root
            MYSQL_PASSWORD: root  
        volumes: 
            - ./mysql:/var/lib/mysql
        restart: always
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: clinica-phpmyadmin
        restart: always
        ports: 
            - '8080:80'
        environment: 
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root   
    web:
        build: .
        container_name: clinica-php
        ports: 
            - '80:80'
        volumes: 
            - ./www:/var/www/html
        links: 
            - mysql
        restart: always

            

    
        