version: '2'
services:
    mysql:
        container_name: paginasql
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - '8889:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: pagina_2  
            MYSQL_USER: root
            MYSQL_PASSWORD: root  
        volumes: 
            - ./mysql:/var/lib/mysql
        restart: always
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: pagina-phpmyadmin
        restart: always
        ports: 
            - '3001:80'
        environment: 
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root   
    web:
        build: .
        container_name: pagina-php
        ports: 
            - '8880:80'
        volumes: 
            - ./www:/var/www/html
        links: 
            - mysql
        restart: always

            

    
        